// Airport data (since DB keeps timing out, use in-memory data)
export const airportsDatabase = [
  { code: 'ATL', name: 'Hartsfield-Jackson Atlanta International Airport', city: 'Atlanta', state: 'GA', lat: 33.6367, lon: -84.4281 },
  { code: 'DFW', name: 'Dallas/Fort Worth International Airport', city: 'Dallas', state: 'TX', lat: 32.8998, lon: -97.0403 },
  { code: 'DEN', name: 'Denver International Airport', city: 'Denver', state: 'CO', lat: 39.8561, lon: -104.6737 },
  { code: 'ORD', name: "O'Hare International Airport", city: 'Chicago', state: 'IL', lat: 41.9742, lon: -87.9073 },
  { code: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', state: 'CA', lat: 33.9425, lon: -118.4081 },
  { code: 'CLT', name: 'Charlotte Douglas International Airport', city: 'Charlotte', state: 'NC', lat: 35.2140, lon: -80.9431 },
  { code: 'MCO', name: 'Orlando International Airport', city: 'Orlando', state: 'FL', lat: 28.4179, lon: -81.3089 },
  { code: 'LAS', name: 'Harry Reid International Airport', city: 'Las Vegas', state: 'NV', lat: 36.0840, lon: -115.1537 },
  { code: 'PHX', name: 'Phoenix Sky Harbor International Airport', city: 'Phoenix', state: 'AZ', lat: 33.4373, lon: -112.0078 },
  { code: 'MIA', name: 'Miami International Airport', city: 'Miami', state: 'FL', lat: 25.7959, lon: -80.2870 },
  { code: 'SEA', name: 'Seattle-Tacoma International Airport', city: 'Seattle', state: 'WA', lat: 47.4502, lon: -122.3088 },
  { code: 'IAH', name: 'George Bush Intercontinental Airport', city: 'Houston', state: 'TX', lat: 29.9902, lon: -95.3368 },
  { code: 'EWR', name: 'Newark Liberty International Airport', city: 'Newark', state: 'NJ', lat: 40.6895, lon: -74.1745 },
  { code: 'MSP', name: 'Minneapolis-St Paul International Airport', city: 'Minneapolis', state: 'MN', lat: 44.8848, lon: -93.2223 },
  { code: 'BOS', name: 'Logan International Airport', city: 'Boston', state: 'MA', lat: 42.3656, lon: -71.0096 },
  { code: 'DTW', name: 'Detroit Metropolitan Wayne County Airport', city: 'Detroit', state: 'MI', lat: 42.2162, lon: -83.3554 },
  { code: 'FLL', name: 'Fort Lauderdale-Hollywood International Airport', city: 'Fort Lauderdale', state: 'FL', lat: 26.0742, lon: -80.1506 },
  { code: 'PHL', name: 'Philadelphia International Airport', city: 'Philadelphia', state: 'PA', lat: 39.8729, lon: -75.2437 },
  { code: 'LGA', name: 'LaGuardia Airport', city: 'New York', state: 'NY', lat: 40.7769, lon: -73.8740 },
  { code: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York', state: 'NY', lat: 40.6413, lon: -73.7781 },
  { code: 'BWI', name: 'Baltimore/Washington International Airport', city: 'Baltimore', state: 'MD', lat: 39.1774, lon: -76.6684 },
  { code: 'DCA', name: 'Ronald Reagan Washington National Airport', city: 'Washington', state: 'DC', lat: 38.8512, lon: -77.0402 },
  { code: 'IAD', name: 'Washington Dulles International Airport', city: 'Washington', state: 'VA', lat: 38.9531, lon: -77.4565 },
  { code: 'SLC', name: 'Salt Lake City International Airport', city: 'Salt Lake City', state: 'UT', lat: 40.7899, lon: -111.9791 },
  { code: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco', state: 'CA', lat: 37.6213, lon: -122.3790 },
  { code: 'MDW', name: 'Chicago Midway International Airport', city: 'Chicago', state: 'IL', lat: 41.7868, lon: -87.7522 },
  { code: 'TPA', name: 'Tampa International Airport', city: 'Tampa', state: 'FL', lat: 27.9755, lon: -82.5332 },
  { code: 'PDX', name: 'Portland International Airport', city: 'Portland', state: 'OR', lat: 45.5887, lon: -122.5975 },
  { code: 'HNL', name: 'Daniel K. Inouye International Airport', city: 'Honolulu', state: 'HI', lat: 21.3187, lon: -157.9225 },
  { code: 'SAN', name: 'San Diego International Airport', city: 'San Diego', state: 'CA', lat: 32.7336, lon: -117.1897 },
  { code: 'BNA', name: 'Nashville International Airport', city: 'Nashville', state: 'TN', lat: 36.1263, lon: -86.6774 },
  { code: 'DAL', name: 'Dallas Love Field Airport', city: 'Dallas', state: 'TX', lat: 32.8471, lon: -96.8518 },
  { code: 'AUS', name: 'Austin-Bergstrom International Airport', city: 'Austin', state: 'TX', lat: 30.1945, lon: -97.6699 },
  { code: 'STL', name: 'St. Louis Lambert International Airport', city: 'St. Louis', state: 'MO', lat: 38.7487, lon: -90.3700 },
  { code: 'RDU', name: 'Raleigh-Durham International Airport', city: 'Raleigh', state: 'NC', lat: 35.8776, lon: -78.7875 },
  { code: 'SMF', name: 'Sacramento International Airport', city: 'Sacramento', state: 'CA', lat: 38.6954, lon: -121.5908 },
  { code: 'MCI', name: 'Kansas City International Airport', city: 'Kansas City', state: 'MO', lat: 39.2976, lon: -94.7139 },
  { code: 'CLE', name: 'Cleveland Hopkins International Airport', city: 'Cleveland', state: 'OH', lat: 41.4117, lon: -81.8498 },
  { code: 'OAK', name: 'Oakland International Airport', city: 'Oakland', state: 'CA', lat: 37.7213, lon: -122.2207 },
  { code: 'IND', name: 'Indianapolis International Airport', city: 'Indianapolis', state: 'IN', lat: 39.7173, lon: -86.2944 },
  { code: 'CVG', name: 'Cincinnati/Northern Kentucky International Airport', city: 'Cincinnati', state: 'OH', lat: 39.0488, lon: -84.6678 },
  { code: 'SJC', name: 'Norman Y. Mineta San Jose International Airport', city: 'San Jose', state: 'CA', lat: 37.3626, lon: -121.9291 },
  { code: 'PIT', name: 'Pittsburgh International Airport', city: 'Pittsburgh', state: 'PA', lat: 40.4915, lon: -80.2329 },
  { code: 'SNA', name: 'John Wayne Airport', city: 'Santa Ana', state: 'CA', lat: 33.6757, lon: -117.8682 },
  { code: 'CMH', name: 'John Glenn Columbus International Airport', city: 'Columbus', state: 'OH', lat: 39.9980, lon: -82.8919 },
  { code: 'MKE', name: 'Milwaukee Mitchell International Airport', city: 'Milwaukee', state: 'WI', lat: 42.9472, lon: -87.8966 },
  { code: 'RSW', name: 'Southwest Florida International Airport', city: 'Fort Myers', state: 'FL', lat: 26.5362, lon: -81.7552 },
  { code: 'JAX', name: 'Jacksonville International Airport', city: 'Jacksonville', state: 'FL', lat: 30.4941, lon: -81.6879 },
  { code: 'SAT', name: 'San Antonio International Airport', city: 'San Antonio', state: 'TX', lat: 29.5337, lon: -98.4698 },
  { code: 'MSY', name: 'Louis Armstrong New Orleans International Airport', city: 'New Orleans', state: 'LA', lat: 29.9934, lon: -90.2580 },
  { code: 'MEM', name: 'Memphis International Airport', city: 'Memphis', state: 'TN', lat: 35.0424, lon: -89.9767 },
  { code: 'BDL', name: 'Bradley International Airport', city: 'Hartford', state: 'CT', lat: 41.9389, lon: -72.6860 },
  { code: 'BUF', name: 'Buffalo Niagara International Airport', city: 'Buffalo', state: 'NY', lat: 42.9405, lon: -78.7322 },
  { code: 'OMA', name: 'Eppley Airfield', city: 'Omaha', state: 'NE', lat: 41.3032, lon: -95.8941 },
  { code: 'ABQ', name: 'Albuquerque International Sunport', city: 'Albuquerque', state: 'NM', lat: 35.0402, lon: -106.6090 },
  { code: 'RIC', name: 'Richmond International Airport', city: 'Richmond', state: 'VA', lat: 37.5052, lon: -77.3197 },
  { code: 'OKC', name: 'Will Rogers World Airport', city: 'Oklahoma City', state: 'OK', lat: 35.3931, lon: -97.6007 },
  { code: 'PBI', name: 'Palm Beach International Airport', city: 'West Palm Beach', state: 'FL', lat: 26.6832, lon: -80.0956 },
  { code: 'BUR', name: 'Hollywood Burbank Airport', city: 'Burbank', state: 'CA', lat: 34.2007, lon: -118.3585 },
  { code: 'ANC', name: 'Ted Stevens Anchorage International Airport', city: 'Anchorage', state: 'AK', lat: 61.1744, lon: -149.9964 },
  { code: 'ONT', name: 'Ontario International Airport', city: 'Ontario', state: 'CA', lat: 34.0560, lon: -117.6012 },
  { code: 'RNO', name: 'Reno-Tahoe International Airport', city: 'Reno', state: 'NV', lat: 39.4991, lon: -119.7681 },
  { code: 'TUL', name: 'Tulsa International Airport', city: 'Tulsa', state: 'OK', lat: 36.1984, lon: -95.8882 },
  { code: 'ELP', name: 'El Paso International Airport', city: 'El Paso', state: 'TX', lat: 31.8073, lon: -106.3778 },
  { code: 'CHS', name: 'Charleston International Airport', city: 'Charleston', state: 'SC', lat: 32.8986, lon: -80.0405 },
  { code: 'LGB', name: 'Long Beach Airport', city: 'Long Beach', state: 'CA', lat: 33.8178, lon: -118.1516 },
  { code: 'PVD', name: 'Theodore Francis Green State Airport', city: 'Providence', state: 'RI', lat: 41.7326, lon: -71.4204 },
  { code: 'PWM', name: 'Portland International Jetport', city: 'Portland', state: 'ME', lat: 43.6463, lon: -70.3093 },
  { code: 'BHM', name: 'Birmingham-Shuttlesworth International Airport', city: 'Birmingham', state: 'AL', lat: 33.5629, lon: -86.7536 },
  { code: 'SDF', name: 'Louisville Muhammad Ali International Airport', city: 'Louisville', state: 'KY', lat: 38.1744, lon: -85.7360 },
  { code: 'TUS', name: 'Tucson International Airport', city: 'Tucson', state: 'AZ', lat: 32.1161, lon: -110.9410 },
  { code: 'ALB', name: 'Albany International Airport', city: 'Albany', state: 'NY', lat: 42.7483, lon: -73.8017 },
  { code: 'SYR', name: 'Syracuse Hancock International Airport', city: 'Syracuse', state: 'NY', lat: 43.1112, lon: -76.1063 },
  { code: 'ROC', name: 'Greater Rochester International Airport', city: 'Rochester', state: 'NY', lat: 43.1189, lon: -77.6724 },
  { code: 'ORF', name: 'Norfolk International Airport', city: 'Norfolk', state: 'VA', lat: 36.8946, lon: -76.2012 },
  { code: 'DSM', name: 'Des Moines International Airport', city: 'Des Moines', state: 'IA', lat: 41.5340, lon: -93.6631 },
  { code: 'GRR', name: 'Gerald R. Ford International Airport', city: 'Grand Rapids', state: 'MI', lat: 42.8808, lon: -85.5228 },
  { code: 'LIT', name: 'Bill and Hillary Clinton National Airport', city: 'Little Rock', state: 'AR', lat: 34.7294, lon: -92.2243 },
  { code: 'GSP', name: 'Greenville-Spartanburg International Airport', city: 'Greenville', state: 'SC', lat: 34.8957, lon: -82.2189 },
  { code: 'XNA', name: 'Northwest Arkansas National Airport', city: 'Bentonville', state: 'AR', lat: 36.2819, lon: -94.3068 },
  { code: 'BOI', name: 'Boise Airport', city: 'Boise', state: 'ID', lat: 43.5644, lon: -116.2228 },
  { code: 'TYS', name: 'McGhee Tyson Airport', city: 'Knoxville', state: 'TN', lat: 35.8110, lon: -83.9940 },
  { code: 'ICT', name: 'Wichita Dwight D. Eisenhower National Airport', city: 'Wichita', state: 'KS', lat: 37.6499, lon: -97.4331 },
  { code: 'SAV', name: 'Savannah/Hilton Head International Airport', city: 'Savannah', state: 'GA', lat: 32.1276, lon: -81.2021 },
  { code: 'DAB', name: 'Daytona Beach International Airport', city: 'Daytona Beach', state: 'FL', lat: 29.1799, lon: -81.0581 },
  { code: 'JAN', name: 'Jackson-Medgar Wiley Evers International Airport', city: 'Jackson', state: 'MS', lat: 32.3112, lon: -90.0759 },
  { code: 'MHT', name: 'Manchester-Boston Regional Airport', city: 'Manchester', state: 'NH', lat: 42.9326, lon: -71.4357 },
  { code: 'LEX', name: 'Blue Grass Airport', city: 'Lexington', state: 'KY', lat: 38.0365, lon: -84.6059 },
  { code: 'BTV', name: 'Burlington International Airport', city: 'Burlington', state: 'VT', lat: 44.4719, lon: -73.1533 },
  { code: 'PSP', name: 'Palm Springs International Airport', city: 'Palm Springs', state: 'CA', lat: 33.8297, lon: -116.5070 },
  { code: 'GEG', name: 'Spokane International Airport', city: 'Spokane', state: 'WA', lat: 47.6198, lon: -117.5336 },
  { code: 'COS', name: 'Colorado Springs Airport', city: 'Colorado Springs', state: 'CO', lat: 38.8058, lon: -104.7006 },
  { code: 'MDT', name: 'Harrisburg International Airport', city: 'Harrisburg', state: 'PA', lat: 40.1935, lon: -76.7634 },
  { code: 'FAT', name: 'Fresno Yosemite International Airport', city: 'Fresno', state: 'CA', lat: 36.7762, lon: -119.7181 },
  { code: 'CAE', name: 'Columbia Metropolitan Airport', city: 'Columbia', state: 'SC', lat: 33.9388, lon: -81.1195 },
  { code: 'PNS', name: 'Pensacola International Airport', city: 'Pensacola', state: 'FL', lat: 30.4734, lon: -87.1866 },
  { code: 'SRQ', name: 'Sarasota/Bradenton International Airport', city: 'Sarasota', state: 'FL', lat: 27.3954, lon: -82.5544 },
  { code: 'GSO', name: 'Piedmont Triad International Airport', city: 'Greensboro', state: 'NC', lat: 36.0978, lon: -79.9373 },
  { code: 'LBB', name: 'Lubbock Preston Smith International Airport', city: 'Lubbock', state: 'TX', lat: 33.6637, lon: -101.8229 },
]

export function getAirportByCode(code: string) {
  return airportsDatabase.find(a => a.code === code)
}

export function getAllAirports() {
  return airportsDatabase
}

